version: '3.1'
networks:
  backend:
    external: true
services:
  mycassandra:
    image: cassandra
    networks:
      - backend
    container_name: mycassandra
    ports:
      - "9042:9042"
    expose: [9042]
  springboot-app:
    networks:
      - backend
    ports:
      - "8081:8080"
    expose: [8081]
    build:
      context: .
      args:
        JAR_FILE: /crud_product.jar
    #restart: always
