version: '3.1'
services:
  mycassandra:
    image: cassandra
    container_name: mycassandra
    ports:
      - "9042:9042"
  springboot-app:
    ports:
      - "8081:8081"
    build:
      context: .
      args:
        JAR_FILE: /crud_product.jar
    restart: always
